//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plugin.mysql {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Plugin.mysql.SqlScripts", typeof(SqlScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE EVENT
        /// &lt;event_name&gt;
        /// ON SCHEDULE EVERY &apos;1&apos; SECOND
        /// &lt;ON COMPLETION [NOT] PRESERVE&gt;
        /// &lt;ENABLE | DISABLE&gt;
        /// &lt;COMMENT &apos;comment&apos;&gt;
        /// DO sql_statement
        ///.
        /// </summary>
        internal static string createevent {
            get {
                return ResourceManager.GetString("createevent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE
        ///    /*[DEFINER = { user | CURRENT_USER }]*/
        ///    FUNCTION &lt;func_name&gt; ()
        ///    RETURNS type
        ///    /*LANGUAGE SQL
        ///    | [NOT] DETERMINISTIC
        ///    | { CONTAINS SQL | NO SQL | READS SQL DATA | MODIFIES SQL DATA }
        ///    | SQL SECURITY { DEFINER | INVOKER }
        ///    | COMMENT &apos;string&apos;*/
        ///    BEGIN
        ///
        ///    END
        ///.
        /// </summary>
        internal static string createfunction {
            get {
                return ResourceManager.GetString("createfunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE [UNIQUE] INDEX [index_name} ON [_table_name] (column1, column2).
        /// </summary>
        internal static string createindex {
            get {
                return ResourceManager.GetString("createindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE
        ///    /*[DEFINER = { user | CURRENT_USER }]*/
        ///    PROCEDURE &lt;procedure_name&gt; ()
        ///    /*LANGUAGE SQL
        ///    | [NOT] DETERMINISTIC
        ///    | { CONTAINS SQL | NO SQL | READS SQL DATA | MODIFIES SQL DATA }
        ///    | SQL SECURITY { DEFINER | INVOKER }
        ///    | COMMENT &apos;string&apos;*/
        ///    BEGIN
        ///
        ///    END
        ///.
        /// </summary>
        internal static string createprocedure {
            get {
                return ResourceManager.GetString("createprocedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE
        ///    TRIGGER &lt;trigger_name&gt; BEFORE/AFTER INSERT/UPDATE/DELETE
        ///    ON &lt;table_name&gt;
        ///    FOR EACH ROW BEGIN
        ///
        ///    END
        ///.
        /// </summary>
        internal static string createtrigger {
            get {
                return ResourceManager.GetString("createtrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml  version=&quot;1.0&quot;?&gt;
        ///&lt;SyntaxDefinition name=&quot;Sql_mysql&quot; extensions=&quot;.sql&quot;&gt;
        ///    &lt;Digits name=&quot;Digits&quot; bold=&quot;false&quot; italic=&quot;false&quot; color=&quot;DarkBlue&quot;/&gt;
        ///
        ///    &lt;RuleSets&gt;
        ///        &lt;RuleSet ignorecase=&quot;true&quot;&gt;
        ///            &lt;Delimiters&gt;&amp;amp;&amp;lt;&amp;gt;~!%^*()-+=|\#/{}[]:;&quot;&apos; , .?&lt;/Delimiters&gt;
        ///        
        ///			&lt;Span name=&quot;LineComment&quot; stopateol=&quot;true&quot; bold=&quot;false&quot; italic=&quot;false&quot; color=&quot;Gray&quot; &gt;
        ///				&lt;Begin &gt;--&lt;/Begin&gt;
        ///			&lt;/Span&gt;
        ///
        ///			&lt;Span name=&quot;BlockComment&quot; stopateol=&quot;false&quot; bold=&quot;false&quot; italic=&quot;false&quot; color=&quot;Gray&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string syntax {
            get {
                return ResourceManager.GetString("syntax", resourceCulture);
            }
        }
    }
}
