//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace keygenlib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("keygenlib.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RSAKeyValue&gt;&lt;Modulus&gt;mnPxLWuFBMXU43PDCo1uDVyDIo2Jg4bSQtWqa8V2552ztTWQ+t3g0wGw4dTgF9gKFNDSbUrqnq2szDHYfa6ql8TIrHfuKb+OwfWhldGrxXycqiKm7l2iDJFZFuKCNUdbFpg1FcoMqT1AcrAMtoWxoV+LkEcu33pB876dz3DKYf0=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;P&gt;zE1xkGODe5BZzQr/TV8ae2b2/Qtw37LXm+GUefiklAtv0N0lGGiZ2Yxqciq6yHdsoi4e4S8HT+TwURitQTOHTw==&lt;/P&gt;&lt;Q&gt;wYlHkb5K69J4EhZp0ImCj4AnFfcH8xqooCEx9XWAtOGVM7oRkOxYw3dJKafqoBPDLKIvkzHxdnySEwHpTDNu8w==&lt;/Q&gt;&lt;DP&gt;qx8OyP7hSWT+IqVcdAT9nHEA3bBwiZ41w+YtRACEcVAnBw3EHW63tqVLH3c03eZRwoHY8Yo/mKbMt1BxBdTQNw==&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string privatekey {
            get {
                return ResourceManager.GetString("privatekey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Products&gt;
        ///    &lt;Product 
        ///		shareit_id=&quot;300362697&quot; 
        ///		longtext=&quot;Professional Tools&quot; 
        ///		text=&quot;Professional&quot; 
        ///		name=&apos;pro&apos; 
        ///		hides=&apos;personal,trial&apos;
        ///		hidepurchaselinks=&apos;1&apos;
        ///    &gt;
        ///		
        ///        &lt;Active forever=&quot;1&quot;/&gt;
        ///        &lt;Updates unit=&quot;day&quot; count=&quot;365&quot;/&gt;
        ///        &lt;Support unit=&quot;day&quot; count=&quot;365&quot;/&gt;
        ///		
        ///		&lt;Feature name=&quot;pro&quot;/&gt;
        ///		
        ///		&lt;Feature name=&quot;jobs&quot;/&gt;
        ///		&lt;Feature name=&quot;querydesigner&quot;/&gt;
        ///		&lt;Feature name=&quot;queryhistory&quot;/&gt;
        ///		&lt;Feature name=&quot;dxdriver&quot;/&gt;
        ///		&lt;Feature name=&quot;mssql_backup&quot;/&gt;
        ///		&lt;Feature nam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
    }
}
