//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatAdmin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatAdmin.CoreRes", typeof(CoreRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE
        ///    VIEW &lt;view_name&gt; 
        ///    AS
        ///    (SELECT * FROM ...)
        ///.
        /// </summary>
        internal static string createview {
            get {
                return ResourceManager.GetString("createview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml  version=&quot;1.0&quot;?&gt;
        ///&lt;SyntaxDefinition name=&quot;Sql_generic&quot; extensions=&quot;.sql&quot;&gt;
        ///    &lt;Digits name=&quot;Digits&quot; bold=&quot;false&quot; italic=&quot;false&quot; color=&quot;DarkBlue&quot;/&gt;
        ///
        ///    &lt;RuleSets&gt;
        ///        &lt;RuleSet ignorecase=&quot;true&quot;&gt;
        ///            &lt;Delimiters&gt;&amp;amp;&amp;lt;&amp;gt;~!%^*()-+=|\#/{}[]:;&quot;&apos; , .?&lt;/Delimiters&gt;
        ///        
        ///			&lt;Span name=&quot;LineComment&quot; stopateol=&quot;true&quot; bold=&quot;false&quot; italic=&quot;false&quot; color=&quot;Gray&quot; &gt;
        ///				&lt;Begin &gt;--&lt;/Begin&gt;
        ///			&lt;/Span&gt;
        ///
        ///			&lt;Span name=&quot;BlockComment&quot; stopateol=&quot;false&quot; bold=&quot;false&quot; italic=&quot;false&quot; color=&quot;Gray [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenericSql_Mode {
            get {
                return ResourceManager.GetString("GenericSql_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add
        ///all
        ///alter
        ///analyze
        ///and
        ///as
        ///asc
        ///asensitive
        ///auto_increment
        ///avg
        ///before
        ///betweenboth
        ///bigint
        ///binary
        ///blob
        ///by
        ///call
        ///cascade
        ///case
        ///change
        ///char
        ///character
        ///check
        ///collate
        ///column
        ///condition
        ///constraint
        ///continue
        ///convert
        ///count
        ///create
        ///cross
        ///current_date
        ///current_time
        ///current_timestamp
        ///current_user
        ///cursor
        ///database
        ///databases
        ///date
        ///datetime
        ///day_hour
        ///day_microsecond
        ///day_minute
        ///day_second
        ///dec
        ///decimal
        ///declare
        ///default
        ///delayed
        ///delete
        ///desc
        ///describe
        ///deterministic
        ///distinct
        ///distinctrow
        ///div
        ///double
        ///drop
        ///dual
        ///each
        ///else
        ///elseif
        ///enclosed
        ///escaped [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string keywords {
            get {
                return ResourceManager.GetString("keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Product name=&quot;personal&quot; text=&quot;Personal&quot; longtext=&quot;Personal Tools&quot;&gt;
        ///	&lt;ActiveTo&gt;4000-01-01T00:00:00&lt;/ActiveTo&gt;
        ///	&lt;SupportTo&gt;0001-01-01T00:00:00&lt;/SupportTo&gt;
        ///	&lt;UpdatesTo&gt;4000-01-01T00:00:00&lt;/UpdatesTo&gt;
        ///	
        ///	&lt;Feature name=&quot;csv&quot;/&gt;
        ///	&lt;Feature name=&quot;dbdocswriter&quot;/&gt;
        ///	&lt;Feature name=&quot;excelexport&quot;/&gt;
        ///	&lt;Feature name=&quot;tabletextexport&quot;/&gt;
        ///	&lt;Feature name=&quot;generictunnel&quot;/&gt;
        ///	&lt;Feature name=&quot;databasebackup&quot;/&gt;
        ///&lt;/Product&gt;
        ///.
        /// </summary>
        internal static string personal {
            get {
                return ResourceManager.GetString("personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RSAKeyValue&gt;&lt;Modulus&gt;mnPxLWuFBMXU43PDCo1uDVyDIo2Jg4bSQtWqa8V2552ztTWQ+t3g0wGw4dTgF9gKFNDSbUrqnq2szDHYfa6ql8TIrHfuKb+OwfWhldGrxXycqiKm7l2iDJFZFuKCNUdbFpg1FcoMqT1AcrAMtoWxoV+LkEcu33pB876dz3DKYf0=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;/RSAKeyValue&gt;.
        /// </summary>
        internal static string publickey {
            get {
                return ResourceManager.GetString("publickey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///
        ///&lt;SyntaxDefinition name=&quot;Python&quot; extensions=&quot;.py&quot;&gt;
        ///	&lt;Environment&gt;
        ///		&lt;Default bold=&quot;false&quot; italic=&quot;false&quot; color=&quot;SystemColors.WindowText&quot; bgcolor=&quot;SystemColors.Window&quot; /&gt;
        ///		&lt;Selection bold=&quot;false&quot; italic=&quot;false&quot; color=&quot;SystemColors.HighlightText&quot; bgcolor=&quot;SystemColors.Highlight&quot; /&gt;
        ///		&lt;VRuler bold=&quot;false&quot; italic=&quot;false&quot; color=&quot;SystemColors.ControlLight&quot; /&gt;
        ///		&lt;InvalidLines bold=&quot;false&quot; italic=&quot;false&quot; color=&quot;Red&quot; /&gt;
        ///		&lt;CaretMarker bold=&quot;false&quot; italic=&quot;false&quot; color=&quot;Yellow&quot; /&gt;
        ///		&lt;L [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Python_Mode {
            get {
                return ResourceManager.GetString("Python_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;  
        ///    &lt;head&gt;    
        ///        &lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;    
        ///        &lt;meta name=&quot;generator&quot; content=&quot;PSPad editor, www.pspad.com&quot;&gt;    
        ///        &lt;title&gt;How to import configuration&lt;/title&gt;  
        ///    &lt;/head&gt;  
        ///    &lt;body&gt;
        ///        &lt;ul&gt;
        ///            &lt;li&gt;If you don&apos;t have DatAdmin installed yet (you need version 4.2.5 or newer), download it (for free) from &lt;a href=&apos;http://datadmin.com/en/download&apos;&gt;datadmin.com&lt;/a&gt; and install&lt;/li&gt;
        ///            &lt;li&gt;Double click on attach [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sendconfig_howto {
            get {
                return ResourceManager.GetString("sendconfig_howto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;SyntaxDefinition name = &quot;Template&quot; extensions = &quot;.tpl&quot;&gt;
        ///	&lt;RuleSets&gt;
        ///		&lt;RuleSet ignorecase=&quot;true&quot;&gt;
        ///			&lt;Span name = &quot;PythonCode&quot; rule=&quot;Python&quot;  bold = &quot;false&quot; italic = &quot;false&quot; color = &quot;Black&quot; stopateol = &quot;false&quot;&gt;
        ///				&lt;Begin color=&quot;Black&quot; bgcolor=&quot;Yellow&quot;&gt;&amp;lt;%&lt;/Begin&gt;
        ///				&lt;End color=&quot;Black&quot; bgcolor=&quot;Yellow&quot;&gt;%&amp;gt;&lt;/End&gt;
        ///			&lt;/Span&gt;
        ///			&lt;Span name = &quot;SqlCode&quot; rule=&quot;GenericSql&quot;  bold = &quot;false&quot; italic = &quot;false&quot; color = &quot;Black&quot; stopateol = &quot;false&quot;&gt;
        ///				&lt;Begin color=&quot;Black&quot; bgcolor=&quot;Ye [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_Mode {
            get {
                return ResourceManager.GetString("Template_Mode", resourceCulture);
            }
        }
    }
}
