//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatAdmin.DataSources.D2DX {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatAdmin.DataSources.D2DX.SqlScripts", typeof(SqlScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE d2dx_info (
        ///    par_name VARCHAR(50) NOT NULL PRIMARY KEY,
        ///    par_value VARCHAR(50) NOT NULL
        ///);
        ///
        ///GO
        ///
        ///INSERT INTO d2dx_info (par_name, par_value) VALUES (&apos;dbversion&apos;, &apos;1&apos;);
        ///.
        /// </summary>
        internal static string update_01 {
            get {
                return ResourceManager.GetString("update_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE d2dx_folder (
        ///    id INTEGER NOT NULL PRIMARY KEY,
        ///    parent_id INTEGER NULL,
        ///    folder_name VARCHAR(100) NOT NULL
        ///)
        ///
        ///GO
        ///
        ///CREATE TABLE d2dx_file (
        ///    id INTEGER NOT NULL PRIMARY KEY,
        ///    folder_id INTEGER NOT NULL,
        ///    file_name VARCHAR(100) NOT NULL,
        ///    data_type VARCHAR(10) NULL,
        ///    file_data TEXT NULL
        ///)
        ///
        ///GO
        ///
        ///INSERT INTO d2dx_folder (id, folder_name) VALUES (1, &apos;diagrams&apos;)
        ///
        ///GO
        ///
        ///INSERT INTO d2dx_folder (id, folder_name) VALUES (2, &apos;sqlscripts&apos;)
        ///
        ///GO
        ///
        ///UPDATE d2dx_i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string update_02 {
            get {
                return ResourceManager.GetString("update_02", resourceCulture);
            }
        }
    }
}
